### ISSUE TITLE
[FEATURE]Trigger ray jobs from training containers

### ISSUE THREAD

**Issue by srinivasreddych** [awslabs/aiops-modules#196]
**Describe the solution you'd like**

Please provide a sample for triggering ray jobs from training containers (app specific). for getting started, it could be within the same namespace, but ideally target across namespaces

**Comment by kukushking** [comment]
Example:
```
apiVersion: v1
kind: Service
metadata:
  name: ray-service
  namespace: ray
spec:
  selector:
    ray.io/node-type: head
  ports:
  - port: 8265
    targetPort: 8265
    name: dashboard
  - port: 10001
    targetPort: 10001
    name: client
  - port: 6379
    targetPort: 6379
    name: gcs
  - port: 8000
    targetPort: 8000
    name: serve
  - port: 8080
    targetPort: 8080
    name: metrics
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ray-hello
  namespace: ray
spec:
  template:
    spec:
      subdomain: ray-service
      containers:
      - name: ray-hello
        image: rayproject/ray-ml:2.23.0
        command: ['sh', '-c', 'python -c "import ray; import os; RAY_ADDRESS = os.environ[\"RAY_ADDRESS\"]; ray.init(address=RAY_ADDRESS); print(ray.cluster_resources())"']
        env:
          - name: RAY_ADDRESS
            value: "ray://ray-service:10001"
      restartPolicy: OnFailure
```
