### ISSUE TITLE
[FEATURE] Configurable VPC/accounts for templates module

### ISSUE THREAD

**Issue by kukushking** [awslabs/aiops-modules#24]
**Describe the solution you'd like**
[SageMaker Service Catalog Templates](https://github.com/awslabs/mlops-modules/blob/main/modules/sagemaker/sagemaker-templates-service-catalog/README.md) module currently does not accept pre-prod and prod account ids/regions as inputs, as well as VPC config. We want to be able to configure it using the manifest i.e. create VPCs in other accounts via seed-farmer:
```
name: networking
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.3.0&depth=1
targetAccount: primary
parameters:
  - name: internet-accessible
    value: True
---
name: networking-preprod
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.3.0&depth=1
targetAccount: pre-prod
parameters:
  - name: internet-accessible
    value: False
```
And reference them in the templates module via:
```
name: templates
path: modules/sagemaker/sagemaker-templates-service-catalog
targetAccount: primary
parameters:
...
  - name: preprod_vpc_id
    valueFrom:
      moduleMetadata:
        group: networking
        name: networking-preprod
        key: VpcId
  - name: preprod_subnet_ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: networking-preprod
        key: PrivateSubnetIds
```
## Task
- Add optional vpc id/subnets parameters for templates module for each of the stages in multi-account mlops template. 
- Add parameters as pre-populated template inputs.
